name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0      

    - name: Install npm packages
      run: |
        npm install

    - name: Format and lint
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm run test

    - name: Run build
      run: |
        npm run build
