name: npm-install-and-use-package

on:
  push:
    branches: [ master ]

jobs:
  npm-install-and-use-package:
    name: npm-install-and-use-package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0

    - name: Install latest npm package in sample app
      working-directory: example/
      run: |
        npm install
        
    - name: Run published package using sample app
      working-directory: example/
      run: |
        npm run dev      